import Footer from '@/Components/layouts/Footer';
import Navbar from '@/Components/layouts/Navbar';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Care.io',
  description: 'Generated by create Care.io',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-base-100 mx-auto">
          <div className="py-2 md:w-11/12 mx-auto">
            <Navbar></Navbar>
          </div>
        </header>
        <main className="py-2 md:w-11/12 mx-auto">{children}</main>
        <footer className="bg-base-100 mx-auto">
          <div className="py-2 md:w-11/12 mx-auto">
            <Footer></Footer>
          </div>
        </footer>
      </body>
    </html>
  );
}
