import { Fredoka, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
 export const fredoka = Fredoka({
  subsets: ['latin'],


});

export const metadata = {
  title: 'Care.io',
  description: 'Generated by create Care.io',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${fredoka.className} `}
      >
        {children}
      </body>
    </html>
  );
}
